### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by BernardOng** [jhykes/retirement-mc#1]
shiller.py is referencing a file that does not exist anymore.
i.e.
http://www.econ.yale.edu/~shiller/data/chapt26.xls

Can you point me in the right direction to the right source?
Thank you.

**Comment by jhykes** [comment]
I see that the file was updated to *.xlsx. I updated the URL: https://github.com/jhykes/retirement-mc/blob/master/shiller/shiller.py#L20

See commit 1cc75d37a966a5db3a903ed37d7e06dafeb97923.
